language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- cd frontend && npm i && npm run build
true:
  branch: master
env:
  global:
  - secure: mV1c1EjxKm9GTDHHnXnqsp0OMvYe4+gqHq89twJiM2mRsx6TCkXfzqIlr/xP7mSRomi/4qlxLoIzVQ9yvZTMDMxO4jwzC5DKXhADFEGTwG1oSe40GtbKOswkmwmKatRFthlvisNNAEST5COLY6GgGFTciI3RR2HISPiNwUDZ7DuI4LBjiAqvo81aO7GMIvQGnZIOf65p/FBG/7bz91C+tz+6y5VsrFPWETm5BiuuG1ozD1q2z4jk0Z77yNtYP+5DItzTCdLDFLZA/KFTvktYlX6HIdYwKXs2/FBzcpwJ4MfaEWr9RSIKqnkcP0hGhlp24ou41NHkwZcwRJCHPUqe8D/nE2QPdu5c3CeYlWcNqN4AJ8ec/jSB17BY7XmJ7+eAmCVSHr3OvHC2xMvcDVDz/+2ijyChVUIrh17WVnn8xKRTfj0lg7NmX/iaDyszrxSVdqQgUkzYAw/MayDY5eP35wFQA4Guwtqao7bj/bsN6F58m3cq7EQbNh97nFmrxxGqJjUuzr8FWFttdfqpPkIv5TSPBYLM1D9a9XqUbC1i2yunIktoZZT/pnRtK083IcWiqhKiRIojXusVAZhba+WhYbGv+Xq/cL66sk52o3YrdXdVN6HqRz+SZDScX3J7NnK40AqAZpIxbcpkN+ER2h118aNbC5WARv2aUAkg1Md8/kU=
  - secure: S56raaT8jRyVCVCzHKpl+s6v6mlC+KdGDB41r2AMT26gstILXlLh2TZ1xndPBmxA4Txa7fj2HhOftbz/91PWrsl8b7ZT7yG08o4VoSpmKhqwSBRsoWmq85xUyJVWouFbLDB34e39UUgkcUiLnlUCAhB1793u6EMZVTCVGCxVqSVB2E5FjdY9AnjrQFMcRkKfDdvAuuncUhwf2i/XApzLxG2WEBjprjfaOISmSQ/rIKVa7BwjLOrEWCJ1s+1bUCJO2FtOdqK58JplDrOt5U40usz+WCv9TEvEYDvHF9JVX4odcUD4IJ3mOE0/TarFzUmWItdP0Lzfe2LsDnsND1BEoBwMKS2dT3UZaIk89Po/q9qFSJ0lMkBlm88XIIJiBtks8eC9BAuwpFWYGeaiCuq/vNUVjBOa6naCaw+rpVjiSHQ/T26FRM31gzYLmwdH0BFe3F6G/nUVTmFEhFo8R4cKVJgXn9wjE6Lk8RG1J7BIL75Zucghi4fAspgTuXfwm3xDWyIJm3LNC911GBvbPIqAiV6amO6HK8cPMIUSXeIo4fvI1UddUs1asY/sBGmsG1ECyCN1vFmIWUzZH6YvFcPjCBd246wRbwDV5q4/rFfXxQKvoS0Lqmi84G5J5qnasCLg6hXPDj/gZKWf+cqWbzXZv7hbkeB7+EmFvhEeUNx6Svo=
