#+TITLE: Scrum 2 Meeting Notes

* Joshua Min
  - Since last meeting I added Travis CI to the project repo.
  - Unfamiliarity with using travis in a multi-language monorepo is keeping me from implementing CI checks on the backend
  - By next meeting I will add our backend and backend tests to Travis.
* Patrick Pacheco
  - Since last meeting, I updated the code for radius to ensure that the respective test passes.
  - N/A
  - By next meeting, I will create a test and code for a route so that the frontend is able to call the backend to store the current user’s session id.
* PJ Hernandez
  - Since last meeting, I have completed the conversion from miles to meters in the radius search for the restaurant. 
  - I was also supposed to add the session based on user login implementation in the backend with Patrick, but due to conflicting schedules we could not meet. 
  - For next meeting, me and Patrick should be able to complete the storing of the user’s current session id, as well as, save recently searched queries.
* Nhan Tran
  - Since the last meeting (sprint planning session), I worked on adding more test case, and error handling for HomePage
  - N/A
  - By next meeting I’ll have the new UI done based on feedback from TA.
